### ISSUE TITLE
 org.bukkit.command.CommandException: Cannot execute command 'ge' in plugin GodsEye vBuild 39 RELEASE - plugin is disabled.

### ISSUE THREAD

**Issue by apholdings** [Nort721/GodsEye#264]
I installed the plugin and ProtocolLib 1.16.x, then proceeded to test if the plugin was installed so i ran: /ge verbose

I got this error: 
org.bukkit.command.CommandException: Cannot execute command 'ge' in plugin GodsEye vBuild 39 RELEASE - plugin is disabled.

"plugin is disabledd" how do i enable the plugin?

Here's the complete conssole output:

[15:08:00 INFO]: VintageRoots issued server command: /ge verbose
[15:08:00 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ge' in plugin GodsEye vBuild 39 RELEASE - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.3.jar:git-Paper-245]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-245]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
>
> org.bukkit.command.CommandException: Cannot execute command 'ge' in plugin GodsEye vBuild 39 RELEASE - plugin is disabled.

**Comment by apholdings** [comment]
Here's the console when the server starts:

[15:14:07 INFO]: [GodsEye] Enabling GodsEye vBuild 39 RELEASE
[15:14:08 INFO]: [GodsEye] activation failed!
[15:14:08 INFO]: [GodsEye] Your GodsEye copy is not activated for an unknown reason, please contact TopRaider or Nort721 for manual activation
[15:14:08 INFO]: [GodsEye] Disabling GodsEye vBuild 39 RELEASE
[15:14:08 INFO]: [GodsEye] has been disabled

Where do i enable my license? bought it on spigotmc

**Comment by BartomeuOut** [comment]
did you try to contact TopRaider or Nort721? 😳

**Comment by Nort721** [comment]
I'm pretty sure we have activated your copy already, if not DM us on discord
