### ISSUE TITLE
Console Errors Flooding (PlayerMoveEvent, NullPointerException and ViaVersion Head Packets) with Build 40 HotFix-1

### ISSUE THREAD

**Issue by mokdennie26** [Nort721/GodsEye#296]
### General Info
1) GodsEye version: Build 40 HotFix-1
2) Server Version: Spigot 1.8.8 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
3) ProtocolLib version: 4.5.1, as instructed on GodsEye's Spigot Page.

### Problem Description
This problem does not have a significant impact on server performance, just some errors spamming in the console after installing Build 40 Hotfix-1.

**PlayerMoveEvent:**
I'm not sure how to reproduce this issue. It just appears when a few players were pvping, and then at some point, it just started to spam the console.
> [02:25:53 ERROR]: Could not pass event PlayerMoveEvent to GodsEye vBuild 40 HotFix-1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_262]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_262]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.ArrayIndexOutOfBoundsException

**NullPointerException:**
I'm not sure how to reproduce this issue. It just appears when a few players were pvping, and then at some point, it just started to spam the console.
> [02:50:04 WARN]: [GodsEye] Task #1053507 for GodsEye vBuild 40 HotFix-1 generated an exception
java.lang.NullPointerException
at godseye.L.a(L.java:104) ~[?:?]
at godseye.ei.f(ei.java:52) ~[?:?]
at godseye.eT.a(eT.java:13) ~[?:?]
at godseye.eL.run(eL.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**onPacketReceiving:**

> [GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent) for GodsEye
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_262]
at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_262]
at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getEntities(CraftWorld.java:626) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at godseye.ey.a(ey.java:51) ~[GodsEye.jar:?]
at godseye.da.lambda$null$0(da.java:217) ~[GodsEye.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_262]
at godseye.da.lambda$onPacketReceiving$1(da.java:214) ~[GodsEye.jar:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_262]
at godseye.da.onPacketReceiving(da.java:214) ~[GodsEye.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:350) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:315) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:538) [ProtocolLib.jar:4.5.1]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-e1ebe52]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.1]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [server.jar:git-Spigot-21fe707-e1ebe52]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**ViaVersion Head Packets:**
(this is triggered whenever a player joins the server):

> [ViaVersion] Received an head update packet, but there is no head! O_o CompoundTag { {Rot=ByteTag(Rot) { 0 }, x=IntTag(x) { 1204 }, y=IntTag(y) { 4 }, z=IntTag(z) { 325 }, id=StringTag(id) { minecraft:skull }, SkullType=ByteTag(SkullType) { 0 }} }

Thanks.

**Comment by Nort721** [comment]
These errors looks really weird, will have a look at them when I can
