### ISSUE TITLE
Random errors in console: Unhandled exception

### ISSUE THREAD

**Issue by Virologicbody** [Nort721/GodsEye#395]
A bug report/issue report should contain:

1) GodsEye version
Build 49

2) Server Version+Fork
Paper 1.17.1 build 137

3) ProtocolLib version
4.7.0

4) Server log
[11:05:48] [Netty Server IO #0/ERROR]: [GodsEye] Unhandled exception number 64 occured in onPacketReceiving(PacketEvent) for GodsEye
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:727) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[?:?]
	at godseye.b8.a(b8.java:27) ~[?:?]
	at godseye.ay.lambda$null$0(ay.java:91) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at godseye.ay.lambda$processIncomingPackets$1(ay.java:87) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at godseye.ay.b(ay.java:87) ~[?:?]
	at godseye.fc.onPacketReceiving(fc.java:47) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-137]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-137]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-137]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 18419.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:265) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[?:?]
	... 59 more
Caused by: java.lang.RuntimeException: An internal error occured.
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:234) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[?:?]
	... 59 more
Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2052) ~[?:?]
	at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:1489) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:234) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[?:?]
	... 59 more

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
Nothing to record/screenshot in-game

6) A very detailed description of the issue
No description from in-game. Just random errors in the console

**Comment by Virologicbody** [comment]
Full server log:

https://pastebin.com/XAbtL2S7

**Comment by Nort721** [comment]
Just released some fixes, we didn't manage to replicate the issue before so if it still happens on new versions, let us know and we will reopen this issue
