### ISSUE TITLE
GodsEye error

### ISSUE THREAD

**Issue by Regomy** [Nort721/GodsEye#415]
> [04:35:46 ERROR]: [GodsEye] Unhandled exception number 256 occured in onPacketReceiving(PacketEvent) for GodsEye
java.lang.NoSuchFieldError: PONG
at godseye.bD.a(bD.java:46) ~[godseye-build-49-hotfix-3.jar:?]
at godseye.c.d(c.java:54) ~[godseye-build-49-hotfix-3.jar:?]
at godseye.bc.onPacketReceiving(bc.java:46) ~[godseye-build-49-hotfix-3.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:348) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:313) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594) [ProtocolLib%20(3).jar:4.6.0]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290) [ProtocolLib%20(3).jar:4.6.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [04:35:48 INFO]: CONSOLE issued server command: /warp respawn Regomy
> [04:35:57 ERROR]: [GodsEye] Unhandled exception number 512 occured in onPacketReceiving(PacketEvent) for GodsEye
java.lang.NoSuchFieldError: PONG
at godseye.bD.a(bD.java:46) ~[godseye-build-49-hotfix-3.jar:?]
at godseye.c.d(c.java:54) ~[godseye-build-49-hotfix-3.jar:?]
at godseye.bc.onPacketReceiving(bc.java:46) ~[godseye-build-49-hotfix-3.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:348) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:313) [ProtocolLib%20(3).jar:4.6.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594) [ProtocolLib%20(3).jar:4.6.0]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290) [ProtocolLib%20(3).jar:4.6.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Nort721** [comment]
You need to update your ProtocolLib version to the latest https://www.spigotmc.org/resources/protocollib.1997/?__cf_chl_jschl_tk__=3wFSU.bO9rSlxNRPsX5UuG17nJBdfK5Y8pp_LkymNic-1636349754-0-gaNycGzNDf0

**Comment by Regomy** [comment]
@Nort721 I`am using godseye and aac 3.3.10, if use protocollib latest version, aac automatically disabling

`Is it possible to make support for an older version of protocollib?

**Comment by Nort721** [comment]
Unfortunately, that's not possible as to make GodsEye support 1.8 to 1.17 it has to use features from latest ProtocolLib that's patched for all of these versions, in addition, I do not recommend running multiple anti-cheats on one server
