### ISSUE TITLE
 [GodsEye] Unhandled exception occured in onPacketReceiving

### ISSUE THREAD

**Issue by ProtoGhost** [Nort721/GodsEye#425]
A bug report/issue report should contain:

GodsEye AntiCheat | Advanced Detection Build 49 HotFix-3
ProtocolLib v4.7.0
paper 1.8.8
This server is running CraftBukkit version git-Spigot-6abac0c-9935adc (MC: 1.8.8)
[ERROR] https://mclo.gs/ss1kjpA

**Comment by Nort721** [comment]
Please provide the full errors, otherwise I can't do much about it

**Comment by ProtoGhost** [comment]
I gave you full error there is nothing more in console

**Comment by ProtoGhost** [comment]
[15:23:13 ERROR]: [GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent) for GodsEye
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_312]
        at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_312]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getEntities(CraftWorld.java:626) ~[server.jar:git-Spigot-21fe707-741a1bd]
        at godseye.c4.a(c4.java:53) ~[GodsEye.jar:?]
        at godseye.b9.lambda$processIncomingPackets$0(b9.java:91) ~[GodsEye.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
        at godseye.b9.lambda$processIncomingPackets$1(b9.java:87) ~[GodsEye.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_312]
        at godseye.b9.b(b9.java:87) ~[GodsEye.jar:?]
        at godseye.fh.onPacketReceiving(fh.java:34) ~[GodsEye.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.0]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-741a1bd]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[15:23:13 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInUseEntity@718e4b8[
    a=6077
    action=ATTACK
    c=<null>
  ]

[15:23:16 WARN]: driggerXD moved wrongly!
[15:23:55 INFO]: [VIII-37] Reddyrocks24 » gg
[15:24:09 INFO]: UUID of player ADITYA466 is 365e8815-c0da-356c-b614-1b1ef088ebbb
[15:24:09 INFO]: [SG-New VV] Player ADITYA466 version: 340
[15:24:09 INFO]: ADITYA466[/106.203.156.119:43886] logged in with entity id 14167 at ([world]17.51438663352586, 87.0, 0.45074090212339146)
[15:24:36 INFO]: UUID of player ahmadtahaa is 370e95aa-b7f8-3019-a416-36c5d3f89140
[15:24:36 INFO]: [SG-New VV] Player ahmadtahaa version: 47
[15:24:36 INFO]: [SG-New VV] Player ahmadtahaa version: 47
[15:24:36 INFO]: ahmadtahaa[/39.37.248.98:37017] logged in with entity id 14490 at ([world]17.51438663352586, 87.0, 0.45074090212339146)
[15:24:51 INFO]: [I-78] RBGMX » i have 5 chestplates,4 boots and 5 swords
[15:24:55 INFO]: UUID of player AVENGER335 is 27fdb79a-7b8a-3519-a031-e7dc22fffe20
[15:24:55 WARN]: [ViaVersion] Ignoring plugin channel in incoming REGISTER: legacy:fml|hs
[15:24:55 WARN]: [ViaVersion] Ignoring plugin channel in incoming REGISTER: dba:
[15:24:55 WARN]: [ViaVersion] Ignoring incoming plugin message with channel: dba:
[15:24:55 INFO]: [SG-New VV] Player AVENGER335 version: 756
[15:24:55 INFO]: AVENGER335[/103.46.200.63:55809] logged in with entity id 14695 at ([world]17.51438663352586, 87.0, 0.45074090212339146)
[15:24:56 WARN]: [ViaVersion] Ignoring incoming plugin message with channel: dba:
[15:24:57 INFO]: [VIII-38] Reddyrocks24 » who tf asked
[15:25:06 INFO]: UUID of player mmokitheboy is 7d55cee7-95e2-33e8-bbce-40f1681fe2b2
[15:25:06 INFO]: [SG-New VV] Player mmokitheboy version: 47
[15:25:06 INFO]: [SG-New VV] Player mmokitheboy version: 47
[15:25:06 INFO]: mmokitheboy[/183.87.193.64:57723] logged in with entity id 14826 at ([world]17.51438663352586, 87.0, 0.45074090212339146)
[15:25:23 INFO]: [VIII-38] Reddyrocks24 » sorry
[15:25:41 INFO]: RBGMX issued server command: /spawn
[15:25:43 INFO]: RBGMX issued server command: /spawn
[15:25:44 INFO]: ADITYA466 issued server command: /spwan
[15:25:45 INFO]: RBGMX issued server command: /spawn
[15:25:47 INFO]: RBGMX issued server command: /spawb
[15:25:50 INFO]: RBGMX issued server command: /soawn gtrhtyg3qrgh5y
[15:25:59 INFO]: RBGMX issued server command: /spawn
[15:26:05 INFO]: [VIII-38] Reddyrocks24 » x1v is drakosha
[15:26:16 INFO]: [DiscordSRV] Chat: DISCORD lonleygirl > i gtg
[15:26:17 INFO]: [VIII-38] Reddyrocks24 » i can ezily tell
[15:27:02 INFO]: [I-78] RBGMX » ahmad
[15:27:22 INFO]: UUID of player Marcuslmao is 67ce85ad-d37b-3f02-9f2e-f83daf48fe65
[15:27:23 INFO]: [SG-New VV] Player Marcuslmao version: 47
[15:27:23 INFO]: [SG-New VV] Player Marcuslmao version: 47
[15:27:23 INFO]: Marcuslmao[/180.191.190.170:56456] logged in with entity id 16825 at ([world]17.51438663352586, 87.0, 0.45074090212339146)
[15:27:32 INFO]: UUID of player chichichigunetka is 4fb84a13-4f84-3a05-82a2-e0ead496d843
[15:27:32 INFO]: [SG-New VV] Player chichichigunetka version: 47
[15:27:32 INFO]: [SG-New VV] Player chichichigunetka version: 47
[15:27:32 INFO]: chichichigunetka[/146.0.62.150:58579] logged in with entity id 17126 at ([world]17.51438663352586, 87.0, 0.45074090212339146)
[15:27:57 INFO]: INFINITE999OP issued server command: /spawn
[15:28:18 WARN]: [ajLeaderboards] Placeholder %thepit_stats_kills% for player ahmadtahaa threw an error:
[15:28:18 WARN]: java.lang.NullPointerException
[15:28:18 WARN]:        at me.mrdarkness462.thepit.features.Placeholders$3.request(Placeholders.java:66)
[15:28:18 WARN]:        at org.magenpurp.api.placeholder.PAPI.onPlaceholderRequest(PAPI.java:42)
[15:28:18 WARN]:        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:34)
[15:28:18 WARN]:        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[15:28:18 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[15:28:18 WARN]:        at us.ajg0702.leaderboards.cache.Cache.updateStat(Cache.java:228)
[15:28:18 WARN]:        at us.ajg0702.leaderboards.cache.Cache.updatePlayerStats(Cache.java:220)
[15:28:18 WARN]:        at us.ajg0702.leaderboards.Main.lambda$reloadInterval$1(Main.java:94)
[15:28:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:28:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:28:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:28:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:28:18 WARN]:        at java.lang.Thread.run(Thread.java:748)
[15:28:18 WARN]: [ajLeaderboards] Placeholder %thepit_stats_assists% for player ahmadtahaa threw an error:
[15:28:18 WARN]: java.lang.NullPointerException
[15:28:18 WARN]:        at me.mrdarkness462.thepit.features.Placeholders$3.request(Placeholders.java:66)
[15:28:18 WARN]:        at org.magenpurp.api.placeholder.PAPI.onPlaceholderRequest(PAPI.java:42)
[15:28:18 WARN]:        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:34)
[15:28:18 WARN]:        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[15:28:18 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[15:28:18 WARN]:        at us.ajg0702.leaderboards.cache.Cache.updateStat(Cache.java:228)
[15:28:18 WARN]:        at us.ajg0702.leaderboards.cache.Cache.updatePlayerStats(Cache.java:220)
[15:28:18 WARN]:        at us.ajg0702.leaderboards.Main.lambda$reloadInterval$1(Main.java:94)
[15:28:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:28:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:28:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:28:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:28:18 WARN]:        at java.lang.Thread.run(Thread.java:748)
[15:28:31 INFO]: XIV issued server command: /spawn
[15:29:28 INFO]: [V-31] PrickoBoi » uh huh
[15:29:35 INFO]: UUID of player dieboipaHD is 249559a2-7524-337b-b2c8-c8055297c52e
[15:29:35 WARN]: [ViaVersion] Ignoring plugin channel in incoming REGISTER: legacy:fml|hs
[15:29:35 WARN]: [ViaVersion] Ignoring plugin channel in incoming REGISTER: dba:
